---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: netflicks
spec:
  selector:
    app: netflicks
  ports:
    - name: "netflicks"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflicks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflicks
  template:
    metadata:
      labels:
        app: netflicks
    spec:
      containers:
      - name: db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "reallyStrongPwd123"

      - name: netflicks
        image: contrastsecuritydemo/netflicks:k8s
        ports:
        - containerPort: 8080
        env: 
        - name: ConnectionStrings__DotNetFlicksConnection
          value: "Server=tcp:localhost,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;"
