---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app.kubernetes.io/instance: netflicks-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "reallyStrongPwd123"
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: netflicks
spec:
  selector:
    app: netflicks
  ports:
    - name: "netflicks"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflicks
  annotations:
    app.openshift.io/connects-to: netflicks-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflicks
  template:
    metadata:
      labels:
        app: netflicks
    spec:
      initContainers:
        - name: check-db
          image: mcr.microsoft.com/mssql-tools:latest
          command:
            - "/opt/mssql-tools/bin/sqlcmd"
            - "-S"
            - "db-service"
            - "-U"
            - "sa"
            - "-P"
            - "reallyStrongPwd123"
      containers:
      - name: netflicks
        image: contrastsecuritydemo/netflicks:k8s
        ports:
        - containerPort: 8080
        env: 
        - name: ConnectionStrings__DotNetFlicksConnection
          value: "Server=tcp:db-service,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netflicks
spec:
  tls:
    termination: edge
  port:
    targetPort: netflicks
  to:
    kind: Service
    name: netflicks
    weight: 100
  wildcardPolicy: None
